sudo: false
language: python
python:
  - "2.7"
  - "3.6"
env:
  - TOXENV=py-pytest
  - TOXENV=py-cram
matrix:
  allow_failures:
    - env: TOXENV=py-cram
      # cram test depends on git version so it may fail with some
      # version of git.
      # TODO: fix git version in CI
before_install:
  - pip install --quiet tox docutils coveralls
  # docutils (rst2man.py) is required during sdist.  That's why it is
  # installed outside tox.
script:
  - tox
after_success:
  - if [ "$TOXENV" = py-pytest ]; then coveralls; fi
notifications:
  email: false
