name: CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
        toxenv: ['py-pytest', 'py-cram']
      fail-fast: false
    name: Test Python ${{ matrix.python-version }} ${{ matrix.toxenv }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install --upgrade tox docutils coveralls
      - run: python -m tox -e ${{ matrix.toxenv }}
      - name: Upload Coverage
        if: ${{ matrix.toxenv == 'py-pytest' }}
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
      - name: Upload coverage to Codecov
        if: ${{ matrix.toxenv == 'py-pytest' }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella

  # Finish parallel build
  # https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#configuration
  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
